config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'categories' => 'static_pages#categories'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'tshirts' => 'static_pages#tshirts'
  get 'sublimation' => 'static_pages#sublimation'
  get 'display' => 'static_pages#display'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def categories
  end

  def about
  end

  def contact
  end

  def tshirts
  end

  def sublimation
  end

  def display
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_bottom_contact_info.html.erb
<div class="row full-width bottom-contact-info">
  <div class="small-12 columns">
    <div class="small-6 columns">
      <i class="flaticon-phone"></i>
      <a href="tel:01912324232">+44 1323891</a>
      <span class="opening-time">Mon-Fri 8am-5pm</span>
    </div>
    <div class="small-6 columns">
      <i class="flaticon-mail"></i>
      <%= link_to "Contact", contact_path %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="row full-width footer">
  <div class="small-12 small-centered columns footer-container animated">
  <div class="small-12 medium-4 columns">
    <div class="row">
      <div class="small-12 columns footer-content">
        <h3>About Us</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
      </div>
      <div class="small-12 columns footer-content footer-contact">
        <h3>FranklinPrint: Contact</h3>
        <a href="#" class="flaticon-phone">0123456789</a>
        <a href="#" class="flaticon-mail">contact@franklinprint.co.uk</a>
      </div>
    </div>
  </div>
  <div class="small-12 medium-4 columns">
    <div class="small-12 columns footer-content">
      <h3>Services</h3>
      <ul class="footer-services">
        <li><a href="#">T-shirt printing</a></li>
        <li><a href="#">Workwear</a></li>
        <li><a href="#">Dye sublimation</a></li>
        <li><a href="#">Display printing</a></li>
        <li><a href="#">Charity vests</a></li>
      </ul>
    </div>
    <div class="small-12 columns footer-content">
      <h3>Locations</h3>
      <p>We supply to anywhere in Europe</p>
      <p>England, France, Italy, Spain, Germany, Poland, Sweden</p>
    </div>
  </div>
  <div class="small-12 medium-4 columns">
    <div class="small-12 columns footer-content">
      <h3>Map</h3>
      <div id="map"></div>
      <span class="address">
        <p>123 Fake Street</p>
        <p>City</p>
        <p>Country</p>
        <p>Post code</p>
      </span>
    </div>
  </div>
</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
    <h1><a href="#">FranklinPrint</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="active"><%= link_to "Home", root_path %></li>
      <li class="has-dropdown">
      <a href="#">Services</a>
      <ul class="dropdown">
        <li><%= link_to "T-shirt printing", tshirts_path %></li>
        <li><%= link_to "Workwear", tshirts_path %></li>
        <li><%= link_to "Sublimation printing", sublimation_path %></li>
        <li><%= link_to "Display printing", display_path %></li>
        <li><%= link_to "Charity vests", sublimation_path %></li>
      </ul>
      </li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </section>
</nav>
<hr class="nav-hr" />

app/views/layouts/_top_contact_info.html.erb
<div class="row full-width">
  <div class="small-12 medium-4 columns top-social-icons right">
    <a href="#" class="flaticon-google-plus"></a>
    <a href="#" class="flaticon-twitter"></a>
    <a href="#" class="flaticon-facebook"></a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Printing website" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>
    </head>

  <body>
    <%= render 'layouts/top_contact_info' %>
    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "#{Rails.root}/app/assets/javascripts/css3-animate-it.js" %>
  </body>
</html>

app/views/static_pages/_sales_pitch.html.erb
<div class="row full-width sales-pitch">
  <div class="row">
  <div class="small-12 medium-4 columns animatedParent">
    <div class="animated bounceInLeft">
    <i class="flaticon-service"></i>
    <h2>Quality services</h2>
    <p>We pride ourselves on supplying the best quality of service to all of our customers</p>
    <a href="#" class="button">See more</a>
  </div>
  </div>
  <div class="small-12 medium-4 columns animatedParent">
    <div class="animated bounceInUp">
    <i class="flaticon-cogs"></i>
    <h2>Industry experience</h2>
    <p>We're experts in our field. With over 30 years experience you can be sure you're in safe hands</p>
    <%= link_to 'See more', about_path, class: "button" %>
  </div>
  </div>
  <div class="small-12 medium-4 columns animatedParent">
    <div class="animated bounceInRight">
    <i class="flaticon-client"></i>
    <h2>Customer satisfaction</h2>
    <p>Our customers are always happy with the level of quality, support and service they receieve from us.</p>
    <a href="#" class="button">See more</a>
  </div>
  </div>
</div>
</div>
<hr />

app/views/static_pages/_slider.html.erb
<div class="row full-width">
  <div class="small-12 small-centered columns home-banner">
    <ul data-orbit data-options="slide_number: false; animation: 'fade'; bullets: false; animation_speed: 300;">
      <li>
      <h2>From business cards to custom t-shirts we have you covered</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas bibendum leo est, nec fringilla turpis rutrum facilisis. Maecenas at placerat orci, sed varius nisl. Ut pellentesque convallis maximus. Proin eget lectus urna. Curabitur in dui molestie, accumsan diam nec, sagittis ex.</p>
      <a href="#" class="button radius large-3">Get in touch</a>
      <%= image_tag "banner.jpg" %>
      </li>
      <li>
      <h2>Custom t-shirt printing</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas bibendum leo est, nec fringilla turpis rutrum facilisis. Maecenas at placerat orci, sed varius nisl. Ut pellentesque convallis maximus. Proin eget lectus urna. Curabitur in dui molestie, accumsan diam nec, sagittis ex.</p>
      <a href="#" class="button radius large-3">See more</a>
      <%= image_tag "banner2.gif" %>
      </li>
      <li>
      <h2>Get a display made</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas bibendum leo est, nec fringilla turpis rutrum facilisis. Maecenas at placerat orci, sed varius nisl. Ut pellentesque convallis maximus. Proin eget lectus urna. Curabitur in dui molestie, accumsan diam nec, sagittis ex.</p>
      <a href="#" class="button radius large-3">Take a look</a>
      <%= image_tag "banner.jpg" %>
      </li>
    </ul>
  </div>
</div>
<hr />

app/views/static_pages/_testimonials.html.erb
<div class="row full-width animatedParent" id="testimonials">
  <div class="row animated bounceInRight">
    <div class="small-12 small-centered columns">
      <h3>Testimonials</h3>
    <div class="large-4 small-12 columns">
      <p class="testimonial">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus varius fringilla odio, at auctor ipsum egestas id.</p>
      <hr />
      <div class="large-10 small-12 small-centered columns person">
      <%= image_tag "testimonial.jpg" %>
      <p>
        <span class="name">John Williams</span>
        <span class="satisfied">Satisfied customer</span>
      </p>
      </div>
    </div>
    <div class="large-4 small-12 columns">
      <p class="testimonial">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus varius fringilla odio, at auctor ipsum egestas id.</p>
      <hr />
      <div class="large-10 small-12 small-centered columns person">
      <%= image_tag "testimonial2.jpg" %>
      <p>
        <span class="name">Kim Jones</span>
        <span class="satisfied">Satisfied customer</span>
      </p>
      </div>
    </div>
    <div class="large-4 small-12 columns">
      <p class="testimonial">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus varius fringilla odio, at auctor ipsum egestas id.</p>
      <hr />
      <div class="large-10 small-12 small-centered columns person">
      <%= image_tag "testimonial3.jpg" %>
      <p>
        <span class="name">Steve Smith</span>
        <span class="satisfied">Satisfied customer</span>
      </p>
      </div>
    </div>
  </div>
  </div>
</div>
<hr />

app/views/static_pages/about.html.erb
<div class="row full-width about">
  <div class="small-12 small-centered columns">
    <h1>About FranklinPrint</h1>
    <%= image_tag "about1.jpg" %>
    <div class="animatedParent">
      <div class="animated bounceInLeft">
        <h2>What We Do</h2>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec mollis. Quisque convallis libero in sapien pharetra tincidunt. Aliquam elit ante, malesuada id, tempor eu, gravida id, odio. Maecenas suscipit, risus et eleifend imperdiet, nisi orci ullamcorper massa, et adipiscing orci velit quis magna. Praesent sit amet ligula id orci venenatis auctor. Phasellus porttitor, metus non tincidunt dapibus, orci pede pretium neque, sit amet adipiscing ipsum lectus et libero. Aenean bibendum. Curabitur mattis quam id urna. Vivamus dui. Donec nonummy lacinia lorem. Cras risus arcu, sodales ac, ultrices ac, mollis quis, justo. Sed a libero. Quisque risus erat, posuere at, tristique non, lacinia quis, eros.</p>
        <p>Cras volutpat, lacus quis semper pharetra, nisi enim dignissim est, et sollicitudin quam ipsum vel mi. Sed commodo urna ac urna. Nullam eu tortor. Curabitur sodales scelerisque magna. Donec ultricies tristique pede. Nullam libero. Nam sollicitudin felis vel metus. Nullam posuere molestie metus. Nullam molestie, nunc id suscipit rhoncus, felis mi vulputate lacus, a ultrices tortor dolor eget augue. Aenean ultricies felis ut turpis. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Suspendisse placerat tellus ac nulla. Proin adipiscing sem ac risus. Maecenas nisi. Cras semper.</p>
        <p>Praesent interdum mollis neque. In egestas nulla eget pede. Integer eu purus sed diam dictum scelerisque. Morbi cursus velit et felis. Maecenas faucibus aliquet erat. In aliquet rhoncus tellus. Integer auctor nibh a nunc fringilla tempus. Cras turpis urna, dignissim vel, suscipit pulvinar, rutrum quis, sem. Ut lobortis convallis dui. Sed nonummy orci a justo. Morbi nec diam eget eros eleifend tincidunt.</p>
      </div>
    </div>
      <%= image_tag "about2.jpg" %>
    <div class="animatedParent">
      <div class="animated bounceInLeft">
        <h2>Our Services</h2>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec mollis. Quisque convallis libero in sapien pharetra tincidunt. Aliquam elit ante, malesuada id, tempor eu, gravida id, odio. Maecenas suscipit, risus et eleifend imperdiet, nisi orci ullamcorper massa, et adipiscing orci velit quis magna. Praesent sit amet ligula id orci venenatis auctor. Phasellus porttitor, metus non tincidunt dapibus, orci pede pretium neque, sit amet adipiscing ipsum lectus et libero. Aenean bibendum. Curabitur mattis quam id urna. Vivamus dui. Donec nonummy lacinia lorem. Cras risus arcu, sodales ac, ultrices ac, mollis quis, justo. Sed a libero. Quisque risus erat, posuere at, tristique non, lacinia quis, eros.</p>
        <p>Cras volutpat, lacus quis semper pharetra, nisi enim dignissim est, et sollicitudin quam ipsum vel mi. Sed commodo urna ac urna. Nullam eu tortor. Curabitur sodales scelerisque magna. Donec ultricies tristique pede. Nullam libero. Nam sollicitudin felis vel metus. Nullam posuere molestie metus. Nullam molestie, nunc id suscipit rhoncus, felis mi vulputate lacus, a ultrices tortor dolor eget augue. Aenean ultricies felis ut turpis. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Suspendisse placerat tellus ac nulla. Proin adipiscing sem ac risus. Maecenas nisi. Cras semper.</p>
        <p>Praesent interdum mollis neque. In egestas nulla eget pede. Integer eu purus sed diam dictum scelerisque. Morbi cursus velit et felis. Maecenas faucibus aliquet erat. In aliquet rhoncus tellus. Integer auctor nibh a nunc fringilla tempus. Cras turpis urna, dignissim vel, suscipit pulvinar, rutrum quis, sem. Ut lobortis convallis dui. Sed nonummy orci a justo. Morbi nec diam eget eros eleifend tincidunt.</p>
      </div>
    </div>
    <div class="animatedParent">
      <div class="animated bounceInUp">
        <h2>Why Work With Us?</h2>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec mollis. Quisque convallis libero in sapien pharetra tincidunt. Aliquam elit ante, malesuada id, tempor eu, gravida id, odio. Maecenas suscipit, risus et eleifend imperdiet, nisi orci ullamcorper massa, et adipiscing orci velit quis magna. Praesent sit amet ligula id orci venenatis auctor. Phasellus porttitor, metus non tincidunt dapibus, orci pede pretium neque, sit amet adipiscing ipsum lectus et libero. Aenean bibendum. Curabitur mattis quam id urna. Vivamus dui. Donec nonummy lacinia lorem. Cras risus arcu, sodales ac, ultrices ac, mollis quis, justo. Sed a libero. Quisque risus erat, posuere at, tristique non, lacinia quis, eros.</p>
        <p>Cras volutpat, lacus quis semper pharetra, nisi enim dignissim est, et sollicitudin quam ipsum vel mi. Sed commodo urna ac urna. Nullam eu tortor. Curabitur sodales scelerisque magna. Donec ultricies tristique pede. Nullam libero. Nam sollicitudin felis vel metus. Nullam posuere molestie metus. Nullam molestie, nunc id suscipit rhoncus, felis mi vulputate lacus, a ultrices tortor dolor eget augue. Aenean ultricies felis ut turpis. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Suspendisse placerat tellus ac nulla. Proin adipiscing sem ac risus. Maecenas nisi. Cras semper.</p>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="row">
  <div class="medium-6 small-12 small-centered columns contact">
    <label>Name
      <input type="text" placeholder="John Smith" />
    </label>
    <label>Email
      <input type="text" placeholder="enquiry@myemail.com" />
    </label>
    <label>Phone number (optional)
      <input type="text" placeholder="07789654221" />
    </label>
    <label>Message
      <textarea rows="4" cols="50" placeholder="Type your message here..."></textarea>
    </label>
    <input type="submit" class="button radius small-12" value="Send message" />
  </div>
</div>

app/views/static_pages/display.html.erb
<div class="row full-width services">
  <div class="small-12 small-centered columns">
    <h1>Display printing</h1>
    <%= image_tag "banner.jpg" %>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="home">

  <%= render "slider" %>
  <%= render "sales_pitch" %>
  <%= render "testimonials" %>



<div class="row full-width services-text">
  <div class="small-12 small-centered columns services-text-container animatedParent">
    <div class="animated bounceInLeft">
    <h3>T-shirt printing, charity vests, displays, flyers and much more</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas bibendum leo est, nec fringilla turpis rutrum facilisis. Maecenas at placerat orci, sed varius nisl. Ut pellentesque convallis maximus. Proin eget lectus urna. Curabitur in dui molestie, accumsan diam nec, sagittis ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas bibendum leo est, nec fringilla turpis rutrum facilisis. Maecenas at placerat orci, sed varius nisl. Ut pellentesque convallis maximus. Proin eget lectus urna. Curabitur in dui molestie, accumsan diam nec, sagittis ex.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas bibendum leo est, nec fringilla turpis rutrum facilisis. Maecenas at placerat orci, sed varius nisl. Ut pellentesque convallis maximus. Proin eget lectus urna. Curabitur in dui molestie, accumsan diam nec, sagittis ex.</p>
    </div>
  </div>
</div>
</div>

app/views/static_pages/sublimation.html.erb
<div class="row full-width services">
  <div class="small-12 small-centered columns">
    <h1>Sublimation</h1>
    <%= image_tag "banner.jpg" %>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
  </div>
</div>

app/views/static_pages/tshirts.html.erb
<div class="row full-width services">
  <div class="small-12 small-centered columns">
    <h1>T-shirt printing</h1>
    <%= image_tag "banner.jpg" %>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus tellus id enim dignissim egestas. Fusce condimentum lorem sit amet elementum venenatis. Duis ut tortor nibh. Suspendisse non massa auctor, dignissim est nec, dictum leo. Duis libero lorem, vestibulum sed elementum vel, ornare luctus dui. Vestibulum sit amet leo vitae dui interdum pulvinar sit amet eget justo</p>
  </div>
</div>